// Mock data for the schedule
export const mockScheduleData = [
  {
    employee: "John Doe",
    date: "2023-05-15",
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    hours: 8,
    department: "Sales",
  },
  {
    employee: "Jane Smith",
    date: "2023-05-15",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    hours: 8,
    department: "Support",
  },
  {
    employee: "Bob Johnson",
    date: "2023-05-16",
    startTime: "8:00 AM",
    endTime: "4:00 PM",
    hours: 8,
    department: "HR",
  },
  {
    employee: "Alice Williams",
    date: "2023-05-16",
    startTime: "12:00 PM",
    endTime: "8:00 PM",
    hours: 8,
    department: "Sales",
  },
  {
    employee: "Charlie Brown",
    date: "2023-05-17",
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    hours: 8,
    department: "Support",
  },
  {
    employee: "Diana Prince",
    date: "2023-05-17",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    hours: 8,
    department: "HR",
  },
  {
    employee: "John Doe",
    date: "2023-05-18",
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    hours: 8,
    department: "Sales",
  },
  {
    employee: "Jane Smith",
    date: "2023-05-19",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    hours: 8,
    department: "Support",
  },
]

// Mock data for employees
export const mockEmployeeData = [
  {
    id: "emp001",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "(555) 123-4567",
    department: "Sales",
    role: "Associate",
    hireDate: "2021-03-15",
  },
  {
    id: "emp002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "(555) 234-5678",
    department: "Support",
    role: "Associate",
    hireDate: "2020-06-22",
  },
  {
    id: "emp003",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "(555) 345-6789",
    department: "HR",
    role: "Manager",
    hireDate: "2019-11-05",
  },
  {
    id: "emp004",
    name: "Alice Williams",
    email: "alice.williams@example.com",
    phone: "(555) 456-7890",
    department: "Sales",
    role: "Associate",
    hireDate: "2022-01-10",
  },
  {
    id: "emp005",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    phone: "(555) 567-8901",
    department: "Support",
    role: "Associate",
    hireDate: "2021-08-17",
  },
  {
    id: "emp006",
    name: "Diana Prince",
    email: "diana.prince@example.com",
    phone: "(555) 678-9012",
    department: "HR",
    role: "Associate",
    hireDate: "2020-04-30",
  },
  {
    id: "emp007",
    name: "Edward Norton",
    email: "edward.norton@example.com",
    phone: "(555) 789-0123",
    department: "Sales",
    role: "Manager",
    hireDate: "2018-12-03",
  },
  {
    id: "emp008",
    name: "Fiona Gallagher",
    email: "fiona.gallagher@example.com",
    phone: "(555) 890-1234",
    department: "Support",
    role: "Manager",
    hireDate: "2019-05-22",
  },
]

// Mock data for department resources
export const mockResourcesData = [
  {
    id: "res001",
    title: "Employee Handbook 2023",
    description: "Complete guide to company policies and procedures",
    category: "Policy",
    fileType: "PDF",
    updatedAt: "May 10, 2023",
    updatedBy: "Bob Johnson",
    isRecent: true,
    isFavorite: true,
  },
  {
    id: "res002",
    title: "Time Off Request Form",
    description: "Form for requesting vacation or personal time off",
    category: "Form",
    fileType: "DOCX",
    updatedAt: "April 15, 2023",
    updatedBy: "Jane Smith",
    isRecent: false,
    isFavorite: true,
  },
  {
    id: "res003",
    title: "Safety Training Materials",
    description: "Required annual safety training documents",
    category: "Training",
    fileType: "PDF",
    updatedAt: "March 22, 2023",
    updatedBy: "Edward Norton",
    isRecent: false,
    isFavorite: false,
  },
  {
    id: "res004",
    title: "Department Budget 2023",
    description: "Current fiscal year budget allocation",
    category: "Finance",
    fileType: "XLSX",
    updatedAt: "May 5, 2023",
    updatedBy: "Bob Johnson",
    isRecent: true,
    isFavorite: false,
  },
  {
    id: "res005",
    title: "New Product Launch Guidelines",
    description: "Procedures for upcoming product releases",
    category: "Marketing",
    fileType: "PDF",
    updatedAt: "April 28, 2023",
    updatedBy: "Fiona Gallagher",
    isRecent: true,
    isFavorite: false,
  },
  {
    id: "res006",
    title: "Holiday Schedule 2023",
    description: "List of company holidays and special events",
    category: "Announcement",
    fileType: "PDF",
    updatedAt: "January 5, 2023",
    updatedBy: "Bob Johnson",
    isRecent: false,
    isFavorite: true,
  },
  {
    id: "res007",
    title: "Expense Reimbursement Form",
    description: "Form for submitting business expenses",
    category: "Form",
    fileType: "DOCX",
    updatedAt: "February 12, 2023",
    updatedBy: "Diana Prince",
    isRecent: false,
    isFavorite: false,
  },
  {
    id: "res008",
    title: "Customer Service Guidelines",
    description: "Best practices for customer interactions",
    category: "Training",
    fileType: "PDF",
    updatedAt: "March 17, 2023",
    updatedBy: "Jane Smith",
    isRecent: false,
    isFavorite: false,
  },
]
